theme: jekyll-theme-midnight
title: Welcome to Nathan Perez's SWEN-101 Github site!
description: Hello! My name is Nathan Perez, and I am a first-year Software Engineering major at the Rochester Institute of Technology. 
