theme: jekyll-theme-midnight
title: Welcome to Nathan Perez's SWEN-101 Github site!
description: Hello! My name is Nathan Perez, and I am a first-year Software Engineering major at the Rochester Institute of Technology. 

# About Me
I was born on October 30th, 2002 in the city of Reading, Pennsylvania (think the Reading Railroad from the Monopoly Board!). 
I lived there throughout my entire life up until this past August, when I moved in on-campus at RIT. I went to Berks Catholic High School and graduated with high honors.
Some of my passions and hobbies include creative writing (especially poetry), solving Rubik's Cubes very quickly, and I am on one of RIT's Esports teams.
When I'm not in my dorm studying or working on a project, you'll likely find me hanging out with friends or walking up and down campus at 1 A.M. I chose 
software engineering as my career path because I love creating solutions to common problems and seeing my code utilized by a wide variety of people.

#Things I'm looking forward to in SWEN-101:
- The ability to collaborate with a team on a project and develop effective team-building and project-management skills.
- Learning how to properly network and reach out to those in the Software Engineering industry to expand my professional influence.
- Virtual candy

#Speaking of candy...my favorite food:

**Bold** and _Italic_ and `Code` text

[Link](url) and ![Image](src)
